cert-manager:
  installCRDs: true

minio:
  # The default is... 16 replicas
  # I suppose I could use 3, but the data is all backed by the *same* hetzner volume lol,
  # so even two is maybe overkill? But I'd like to have two *pods*, even if not 2 backing
  # volumes, just for a bit of HA. So I'll set it to 2, rather than 3.
  replicas: 2

  networkPolicy:
    # Ideally, I wouldn't allow access to minio from other namespaces unless the pod has
    # an annotation, regardless of wether it has credentials or not. However, the helm
    # chart doesn't support specifying Namespace selector yet, only a pod selector.
    # So no real network policy enforcement for now
    enabled: false

  resources:
    requests:
      # The default request is... 16Gi
      memory: 256Mi