creation_rules:
  - path_regex: .*secret.*
    age: 'age1prjecmd9pjh2u2pt8fckflkzp3mps88zrextdv0hfmg0sa6l5gqq8uxzjw'

# stores configuration is supported by sops 3.9.0+ only
stores:
  # By configuring json indent, we get spaces instead of tabs for json files,
  # which makes them valid YAML files as well.
  json:
    indent: 4
  json_binary:
    indent: 4
  yaml:
    indent: 2