# Default values for static.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/static-web-server/static-web-server
  pullPolicy: IfNotPresent
  tag: "2-debian"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

repos:
  blog-test:
    repo: https://github.com/yuvipanda/words/
    branch: master
    host: test.yuvi.in
    subPath: public/
  blog:
    repo: https://github.com/yuvipanda/words/
    branch: master
    host: words.yuvi.in
    subPath: public/

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

resources:
  requests:
    # Generally static-web-server is very memory efficient, and only seems to use about 3-4Mb when idle
    memory: 8Mi
    cpu: 1m
  limits:
    memory: 128Mi
    cpu: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
